[package]
name = "rwhoxy"
version = "0.1.0"
authors = ["myuyu <elmyuyu@twitter.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
isahc = "1.4.0"
serde_json = "1.0.65"
clap = "2.33.3"
